mutation saveSettings(
    $contentIndexedMainResourceTypes: String,
    $contentIndexedSubNodeTypes: String,
    $contentIndexedFileExtensions: String,
    $operationsBatchSize: Int,
    $projectId: String,
    $token: String,
    $jahiaApiToken: String,
    $jahiaGraphqlEndpoint: String,
    $dryRun: Boolean,
    $scheduleJobASAP: Boolean,
    $apiBaseUrl: String,
    $userAgent: String,
    $serverName: String,
    $siteServerNames: String
) {
    admin {
        customGpt {
            saveSettings(
                contentIndexedMainResourceTypes: $contentIndexedMainResourceTypes
                contentIndexedSubNodeTypes: $contentIndexedSubNodeTypes
                contentIndexedFileExtensions: $contentIndexedFileExtensions
                operationsBatchSize: $operationsBatchSize
                projectId: $projectId
                token: $token
                jahiaApiToken: $jahiaApiToken
                jahiaGraphqlEndpoint: $jahiaGraphqlEndpoint
                dryRun: $dryRun
                scheduleJobASAP: $scheduleJobASAP
                apiBaseUrl: $apiBaseUrl
                userAgent: $userAgent
                serverName: $serverName
                siteServerNames: $siteServerNames
            )
        }
    }
}
