query {
    admin {
        customGpt {
            settings {
                contentIndexedMainResourceTypes
                contentIndexedSubNodeTypes
                contentIndexedFileExtensions
                operationsBatchSize
                projectId
                projectName
                token
                jahiaUsername
                jahiaPassword
                jahiaServerCookieName
                jahiaServerCookieValue
                jahiaServerCookieDomain
                userAgent
                serverName
                siteServerNames
                dryRun
                scheduleJobASAP
                apiBaseUrl
            }
        }
    }
}
